apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  selector:
    app: mywebapp
  type: NodePort
  ports:
    - port: 80         # port inside the cluster
      targetPort: 80   # port inside the pod/container
      nodePort: 30080